name: Build Bastionfall

on:
  push:
    branches: [ main, "**" ]  # Build on all branches
  pull_request:
    branches: [ "**" ]        # Build on all PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Upload mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: bastionfall-mod
          path: build/libs/*.jar